# アプリ名
spring.application.name=PFC_navi

spring.profiles.active=local

# PostgreSQL 接続設定
#pfc_naviというデータベースを作成する
spring.datasource.url=jdbc:postgresql://localhost:5432/pfc_navi
spring.datasource.username=postgres

# PostgreSQL ドライバ
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate 設定
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# 起動時のテーブル操作
# create: 毎回作り直し
# update: 既存テーブルをなるべく維持して更新
# none: 自動変更しない
spring.jpa.hibernate.ddl-auto=update

# SQLログを表示
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true